#!/usr/bin/env bash
# =============================================================================
# deploy/provision.sh — Provision Azure infrastructure for Discovery Bot v2
#
# Usage: ./deploy/provision.sh <env-name>
# Example: ./deploy/provision.sh myenv
#
# Creates: Resource Group, Cosmos DB, AI Search, Storage, App Insights,
#          AI Foundry, ACR, Container App (with placeholder image), RBAC
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

source "${SCRIPT_DIR}/_helpers.sh"

ENV_NAME="${1:?Usage: $0 <env-name>}"
load_env "$ENV_NAME"
check_prereqs

# ── Create Resource Group ────────────────────────────────────────────────────

log_step "Creating resource group: ${RESOURCE_GROUP} in ${LOCATION}"

az group create \
    --name "${RESOURCE_GROUP}" \
    --location "${LOCATION}" \
    --tags project=discovery-bot-v2 environment="${SUFFIX}" \
    --output none

log_ok "Resource group: ${RESOURCE_GROUP}"

# ── Compile Bicep (for environments that need ARM JSON) ──────────────────────

log_step "Validating Bicep templates"

az bicep build \
    --file "${REPO_ROOT}/infra/main.bicep" \
    --outfile "${REPO_ROOT}/infra/main.json" \
    2>/dev/null

log_ok "Bicep compiled to infra/main.json"

# ── Deploy Infrastructure ────────────────────────────────────────────────────

log_step "Deploying infrastructure (this takes 5-10 minutes)"

# Build parameter overrides
DEPLOY_PARAMS=(
    --name "deploy-disco-bot"
    --resource-group "${RESOURCE_GROUP}"
    --template-file "${REPO_ROOT}/infra/main.bicep"
    --parameters prefix="${PREFIX}"
    --parameters suffix="${SUFFIX}"
    --parameters location="${LOCATION}"
    --parameters deployerObjectId="${DEPLOYER_OBJECT_ID}"
    --parameters conversationMode="${CONVERSATION_MODE}"
    --parameters authMode="${AUTH_MODE}"
    --parameters primaryModelName="${MODEL_DEPLOYMENT_NAME}"
    --parameters cosmosConsistency="${COSMOS_CONSISTENCY}"
    --parameters imageTag=""
)

# Optional: JWT signing key for magic_link auth
if [[ "${AUTH_MODE}" == "magic_link" && -n "${JWT_SIGNING_KEY:-}" ]]; then
    DEPLOY_PARAMS+=(--parameters jwtSigningKey="${JWT_SIGNING_KEY}")
fi

# Optional: Observability
if [[ "${CONVERSATION_MODE}" == "full" ]]; then
    DEPLOY_PARAMS+=(--parameters enableObservability=true)
    if [[ -n "${ALERT_EMAILS:-}" ]]; then
        # Convert comma-separated to JSON array
        IFS=',' read -ra emails <<< "${ALERT_EMAILS}"
        email_json=$(printf '"%s",' "${emails[@]}")
        DEPLOY_PARAMS+=(--parameters "alertEmails=[${email_json%,}]")
    fi
fi

# Run deployment
az deployment group create \
    "${DEPLOY_PARAMS[@]}" \
    --verbose \
    2>&1 | while IFS= read -r line; do
        # Filter verbose output to show only key events
        if echo "$line" | grep -qE "(Accepted|Succeeded|Creating|running)"; then
            log_info "$line"
        fi
    done

# ── Capture Outputs ──────────────────────────────────────────────────────────

log_step "Capturing deployment outputs"

ACR_NAME=$(get_output "ACR_NAME")
ACR_LOGIN_SERVER=$(get_output "ACR_LOGIN_SERVER")
CONTAINER_APP_NAME=$(get_output "CONTAINER_APP_NAME")
CONTAINER_APP_FQDN=$(get_output "CONTAINER_APP_FQDN")
PROJECT_ENDPOINT=$(get_output "PROJECT_ENDPOINT")
COSMOS_ENDPOINT=$(get_output "COSMOS_ENDPOINT")

# Write outputs to a file for other scripts to consume
cat > "${SCRIPT_DIR}/params/${ENV_NAME}.outputs" << EOF
# Auto-generated by provision.sh — do not edit
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
ACR_NAME=${ACR_NAME}
ACR_LOGIN_SERVER=${ACR_LOGIN_SERVER}
CONTAINER_APP_NAME=${CONTAINER_APP_NAME}
CONTAINER_APP_FQDN=${CONTAINER_APP_FQDN}
PROJECT_ENDPOINT=${PROJECT_ENDPOINT}
COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
EOF

log_ok "Outputs saved to deploy/params/${ENV_NAME}.outputs"

# ── Summary ──────────────────────────────────────────────────────────────────

log_step "Provision Complete"

echo ""
echo "  Resource Group:    ${RESOURCE_GROUP}"
echo "  Container App:     ${CONTAINER_APP_NAME}"
echo "  App URL:           https://${CONTAINER_APP_FQDN}"
echo "  ACR:               ${ACR_NAME} (${ACR_LOGIN_SERVER})"
echo "  Foundry Endpoint:  ${PROJECT_ENDPOINT}"
echo "  Cosmos Endpoint:   ${COSMOS_ENDPOINT}"
echo "  Mode:              ${CONVERSATION_MODE} / ${AUTH_MODE}"
echo ""
echo "  Currently running placeholder image."
echo "  Next step: ./deploy/build-and-deploy.sh ${ENV_NAME}"
echo ""
